#spring.profiles.active=develop
spring.profiles.active=production

server.port=8703

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.tomcat.uri-encoding=UTF-8
spring.mandatory-file-encoding=UTF-8

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

mybatis.configLocation=classpath:mybatis-config.xml
mybatis.mapperLocations=classpath:/mapper/**.xml

# NCP Object Storage (S3 compatible)
storage.endpoint=https://kr.object.ncloudstorage.com
storage.region=kr-standard
storage.accessKey=GPhfGukmqlqJW1XzrwD1
storage.secretKey=8rKj3b6y3ROxrUrZD7XaHbF4K2u7PAM2N24ZG5oH
storage.bucket=road-sos

# ??? ?? URL(?? ??? path-style). CDN ?? CDN ????? ??
storage.public-base-url=https://kr.object.ncloudstorage.com/your-bucket


# sos url
sos.url=https://sos.yido.com

weather.forecast.service-key=vBXjtJR4B3mFBym3IHjtUxBfo3XSd%2FO7cmFhG3yLyQ%2Fwa8XLRyB5NzDqRu%2BapI3dlFarhHpHoiayoGMG9pBcew%3D%3D
weather.forecast.api-url=https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getVilageFcst
