# road_sos
spring.main.datasource.hikari.poolName=SpringHikariCP
spring.main.datasource.hikari.driverClassName=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#spring.main.datasource.hikari.jdbcUrl=jdbc:log4jdbc:mysql://10.10.200.201:16530/road_sos?noAccessToProcedureBodies=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul
#spring.main.datasource.hikari.username=yido
#spring.main.datasource.hikari.password=yido$0623!Q
spring.main.datasource.hikari.jdbcUrl=jdbc:log4jdbc:mysql://49.236.136.83:3312/road_sos?noAccessToProcedureBodies=true&characterEncoding=UTF-8&useSSL=false
spring.main.datasource.hikari.username=recruituser
spring.main.datasource.hikari.password=Codyd0217!
spring.main.datasource.hikari.connectionTimeout=3000
spring.main.datasource.hikari.minimumIdle=5
spring.main.datasource.hikari.maximumPoolSize=20
spring.main.datasource.hikari.idleTimeout=600000
spring.main.datasource.hikari.maxLifetime=1800000

# yidohome
spring.yido.datasource.hikari.poolName=SpringHikariCP
spring.yido.datasource.hikari.driverClassName=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#spring.yido.datasource.hikari.jdbcUrl=jdbc:log4jdbc:mysql://10.10.200.201:16530/yidohome?noAccessToProcedureBodies=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul
#spring.yido.datasource.hikari.username=yido
#spring.yido.datasource.hikari.password=yido$0623!Q
spring.yido.datasource.hikari.jdbcUrl=jdbc:log4jdbc:mysql://49.236.136.83:3312/yidohome?noAccessToProcedureBodies=true&characterEncoding=UTF-8&useSSL=false
spring.yido.datasource.hikari.username=recruituser
spring.yido.datasource.hikari.password=Codyd0217!
spring.yido.datasource.hikari.minimumIdle=5
spring.yido.datasource.hikari.maximumPoolSize=20
spring.yido.datasource.hikari.connectionTimeout=30000
spring.yido.datasource.hikari.idleTimeout=30000
spring.yido.datasource.hikari.maxLifeTime=35000
spring.yido.datasource.hikari.leakDetectionThreshold=4000

# kakao geo
kakao.local.search.address.url=https://dapi.kakao.com/v2/local/search/address.json
kakao.local.search.keyword.url=https://dapi.kakao.com/v2/local/search/keyword.json
kakao.local.endpoint=https://dapi.kakao.com/v2/local/geo/coord2address.json
kakao.local.key=ac4275730eada16822bcea1ede02871f
kakao.map.key=8d2a61a4daaae226675c742bba5c46f9

Globals.File.UploadPath = /D:/imageUpload/

server.host.name=http://10.10.85.85:8703
