SET @col_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'ADMIN_USER'
    AND COLUMN_NAME = 'LAST_RECEIPT_GB_CD'
);

SET @ddl := IF(
  @col_exists = 0,
  'ALTER TABLE ADMIN_USER ADD COLUMN LAST_RECEIPT_GB_CD varchar(50) NULL AFTER BIZ_DIV_CD',
  'SELECT 1'
);

PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
